
services:
  secret_santa:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://secret_santa_db:5432/secret_santa
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - secret_santa_db
  secret_santa_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: secret_santa
    volumes:
      - secret_santa_db-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
  web:
    build:
      context: ../frontend/secret_santa_frontend
    ports:
      - "80:80"
    depends_on:
      - secret_santa
volumes:
  secret_santa_db-data: